# New Section

In [7]:
# -------------------------------------------------------------
# STEP 0: INITIAL SETUP
# -------------------------------------------------------------
# Download the gensim library because Colab does not have it by default
!pip install gensim

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

# Simple input data: 3 sentences to test all NLP methods
sentences = [
    "i love python programming",
    "python is great for data science",
    "i love data science"
]


# -------------------------------------------------------------
# TOPIC 1: BAG OF WORDS (BOW)
# -------------------------------------------------------------
print("--- 1. BAG OF WORDS (BOW) ---")

# Initialize the basic word counting tool
bow_tool = CountVectorizer()

# Feed the sentences into the tool to calculate word frequencies
bow_counts = bow_tool.fit_transform(sentences)

# Print the list of all unique single words discovered
print("Vocabulary (Single Words):", bow_tool.get_feature_names_out())

# Convert the frequency data into a readable matrix array table
print("BOW Counts Matrix:\n", bow_counts.toarray())
print("\n")


# -------------------------------------------------------------
# TOPIC 2: N-GRAMS
# -------------------------------------------------------------
print("--- 2. N-GRAMS (BIGRAMS) ---")

# Set range to (2,2) to strictly look for continuous pairs of two words
ngram_tool = CountVectorizer(ngram_range=(2, 2))

# Count the word pairs in our sentences
ngram_counts = ngram_tool.fit_transform(sentences)

# Print out the connected phrases found, like 'data science'
print("N-Grams (Word Pairs):", ngram_tool.get_feature_names_out())

# Show the occurrence matrix table for these word pairs
print("N-Gram Counts Matrix:\n", ngram_counts.toarray())
print("\n")


# -------------------------------------------------------------
# TOPIC 3: TF-IDF
# -------------------------------------------------------------
print("--- 3. TF-IDF ---")

# Initialize the TF-IDF feature extractor to measure word importance
tfidf_tool = TfidfVectorizer()

# Run the tool to calculate the weight scores for each word
tfidf_scores = tfidf_tool.fit_transform(sentences)

# Display the importance values matrix containing decimal scores
print("TF-IDF Scores Matrix:\n", tfidf_scores.toarray())
print("\n")


# -------------------------------------------------------------
# TOPIC 4: WORD2VEC
# -------------------------------------------------------------
print("--- 4. WORD EMBEDDINGS (WORD2VEC) ---")

# Split every sentence into individual string tokens (words)
split_sentences = [s.split() for s in sentences]

# Train a custom Word2Vec model to map each word to 4 numeric coordinates
word_model = Word2Vec(sentences=split_sentences, vector_size=4, window=2, min_count=1)

# Retrieve and print the specific 4 numbers that represent the word 'python'
print("Word2Vec Numbers representing 'python':")
print(word_model.wv['python'])
print("\n")


# -------------------------------------------------------------
# TOPIC 5: GLOVE (Conceptual Note)
# -------------------------------------------------------------
print("--- 5. MENTOR NOTE ON GLOVE ---")
# GloVe models require massive data downloads, so we print the required theory block instead
print("GloVe (Global Vectors) is conceptually identical to Word2Vec.")
print("The primary difference is that Word2Vec trains locally on our short sentences,")
print("whereas GloVe maps words using global statistics learned from billions of internet files.")

--- 1. BAG OF WORDS (BOW) ---
Vocabulary (Single Words): ['data' 'for' 'great' 'is' 'love' 'programming' 'python' 'science']
BOW Counts Matrix:
 [[0 0 0 0 1 1 1 0]
 [1 1 1 1 0 0 1 1]
 [1 0 0 0 1 0 0 1]]


--- 2. N-GRAMS (BIGRAMS) ---
N-Grams (Word Pairs): ['data science' 'for data' 'great for' 'is great' 'love data'
 'love python' 'python is' 'python programming']
N-Gram Counts Matrix:
 [[0 0 0 0 0 1 0 1]
 [1 1 1 1 0 0 1 0]
 [1 0 0 0 1 0 0 0]]


--- 3. TF-IDF ---
TF-IDF Scores Matrix:
 [[0.         0.         0.         0.         0.51785612 0.68091856
  0.51785612 0.        ]
 [0.34949812 0.45954803 0.45954803 0.45954803 0.         0.
  0.34949812 0.34949812]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.         0.57735027]]


--- 4. WORD EMBEDDINGS (WORD2VEC) ---
Word2Vec Numbers representing 'python':
[-0.1253857  -0.09408429  0.18451262 -0.03833678]


--- 5. MENTOR NOTE ON GLOVE ---
GloVe (Global Vectors) is conceptually identical to Word2Vec.
The primary differe